### ISSUE TITLE
certificates for hololens communication

### ISSUE THREAD

**Issue by sasilva1998** [microsoft/HoloLensNavigationForRobots#1]
I am trying to run the project with a hololens2, however, I think I am not getting the communication right. I am not getting any message from the TCP socket in hololens bridge. I believe it is related to the certificate problem. I installed it but still the lock in the webpage of the IP of hololens isn't changed as seen below:

![](http://i.imgur.com/O0nDcwF.png)

I just need to transmit the pointcloud data from the hololens to ROS, don't care about anything else.

Could that be the problem? How could I debug if the hololens are actually sending the data?

**Comment by davidbaumert** [comment]
Hi, It's been a while since I've had this set up and running in my lab, but seem to recall this certificate issue did not prevent operation of our project, it was merely a convenience.  I will set my rig back up early next month and give you a better response.

**Comment by sasilva1998** [comment]
Hi, in the end it all worked. The certificates weren't the issue, the wifi connection I had was the issue and the way I was using the project. I will close the issue, thanks for the response.
